id: I85805108
legacy_id: P009213
ocr_import_info:
  bdrc_scan_id: W23220
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T04:29:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:00:48.542124+00:00'
last_modified: 2022-09-02 09:00:54.997643
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23220
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23220
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་བསྟན་པ་འཛིན་པའི་སྐྱེས་བུ་རྣམས་ཀྱི་བསླབ་བྱ་སྡོམ་གསུམ་བསྟན་པའི་སྙིང་པོ།
  author: ལྷ་བཙུན་ནམ་མཁའ་འཇིགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.8688189264133388
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I0857:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0857
      total_pages: 158
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0857.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8688189264133388
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
