id: I85805108
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:30:52+00:00'
last_modified: '2022-06-08T09:25:29.727322+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23220
  title: སྔ་འགྱུར་བསྟན་པ་འཛིན་པའི་སྐྱེས་བུ་རྣམས་ཀྱི་བསླབ་བྱ་སྡོམ་གསུམ་བསྟན་པའི་སྙིང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6A46:
      image_group_id: I0857
      title: ''
      total_pages: 158
      order: 1
      base_file: 6A46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
